version: '3'
services:
  lumenapp:
    build: .
    volumes: 
      - ./:/var/www
    depends_on: 
      - lumenapp-mysql
      - lumenapp-redis
  
  lumenapp-mysql:
    image: mysql:5.7.22
    command: --innodb-use-native-aio=0
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - "./.docker/dbdata:/var/lib/mysql"
    environment: 
      MYSQL_DATABASE: lumenapp
      MYSQL_ROOT_PASSWORD: root
  
  lumenapp-redis:
    image: redis:alpine
    expose: 
      - 6379

  lumenapp-nginx:
    build: ./.docker/nginx
    restart: always
    ports:
      - "8001:80"
    volumes:
      - ./:/var/www
    depends_on: 
      - lumenapp